services:
  broker-1:
    ports:
      - "39092:39092"

  etl_ugc:
    build:
      context: ./etl_ugc
      dockerfile: ./docker/Dockerfile

  clickhouse-node1:
    ports:
      - "8123:8123"
      - "9100:9000"

  ugc_service:
    build:
      context: ./ugc
      dockerfile: ./docker/Dockerfile
      target: development
    volumes:
      - ./ugc/src:/opt/app
    ports:
        - "8001:8001"

  auth:
    build:
      context: auth
      dockerfile: ./docker/Dockerfile
      target: development
    ports:
      - "5000:5000"

  redis_auth:
    ports:
      - "${REDIS_AUTH_PORT}:6379"

  postgres_auth:
    ports:
      - "${PG_AUTH_PORT}:5432"

  backend:
    restart: "always"
    build:
      context: ./backend
      dockerfile: ./docker/Dockerfile
      target: development
    container_name: backend
    volumes:
      - ./backend/src/:/opt/app/
    ports:
      - "8000:8000"

  redis_backend:
    ports:
      - "${REDIS_BACKEND_PORT}:6379"

  elasticsearch_movies:
    ports:
      - "${ELK_MOVIES_PORT}:9200"

  minio_0:
    ports:
     - "9000:9000"
     - "9001:9001"

  nginx_minio_0:
    ports:
      - "7000:80"

  minio_1:
    ports:
      - "9010:9000"
      - "9011:9001"

  nginx_minio_1:
    ports:
      - "7010:80"

  minio_2:
    ports:
      - "9020:9000"
      - "9021:9001"

  nginx_minio_2:
    ports:
      - "7020:80"
