services:
  broker-1:
    ports:
      - "39092:39092"
    networks:
      default:
        ipv4_address: 172.18.0.50

  etl_ugc:
    build:
      context: ./etl_ugc
      dockerfile: ./docker/Dockerfile
    networks:
      default:
        ipv4_address: 172.18.0.51

  clickhouse-node1:
    ports:
      - "8123:8123"
      - "9100:9000"
    networks:
      default:
        ipv4_address: 172.18.0.52

  ugc_service:
    build:
      context: ./ugc
      dockerfile: ./docker/Dockerfile
      target: development
    volumes:
      - ./ugc/src:/opt/app
    ports:
        - "8001:8001"
    networks:
      default:
        ipv4_address: 172.18.0.53

  auth:
    build:
      context: auth
      dockerfile: ./docker/Dockerfile
      target: development
    ports:
      - "5000:5000"
    networks:
      default:
        ipv4_address: 172.18.0.54

  redis_auth:
    ports:
      - "${REDIS_AUTH_PORT}:6379"
    networks:
      default:
        ipv4_address: 172.18.0.55

  postgres_auth:
    ports:
      - "${PG_AUTH_PORT}:5432"
    networks:
      default:
        ipv4_address: 172.18.0.56

  backend:
    restart: "always"
    build:
      context: ./backend
      dockerfile: ./docker/Dockerfile
      target: development
    container_name: backend
    volumes:
      - ./backend/src/:/opt/app/
    ports:
      - "8000:8000"
    networks:
      default:
        ipv4_address: 172.18.0.57

  redis_backend:
    ports:
      - "${REDIS_BACKEND_PORT}:6379"
    networks:
      default:
        ipv4_address: 172.18.0.58

  elasticsearch_movies:
    ports:
      - "${ELK_MOVIES_PORT}:9200"
    networks:
      default:
        ipv4_address: 172.18.0.59

  minio-0:
    ports:
     - "9000:9000"
     - "9001:9001"
    networks:
      default:
        ipv4_address: 172.18.0.10

  minio-1:
    ports:
      - "9010:9000"
      - "9011:9001"
    networks:
      default:
        ipv4_address: 172.18.0.11

  minio-2:
    ports:
      - "9020:9000"
      - "9021:9001"
    networks:
      default:
        ipv4_address: 172.18.0.12

  prometheus:
    ports:
      - "9090:9090"
    networks:
      default:
        ipv4_address: 172.18.0.60

  admin_movies:
    ports:
      - "${DJANGO_MOVIES_PORT}:8000"
    networks:
      default:
        ipv4_address: 172.18.0.61

  postgres_movies:
    ports:
      - "5436:5432"
    networks:
      default:
        ipv4_address: 172.18.0.62

  load-service-0:
    ports:
      - "8100:8000"
    networks:
      default:
        ipv4_address: 172.18.0.63

  dashboard:
    ports:
      - "5555:5555"
    networks:
      default:
        ipv4_address: 172.18.0.64

  routing-service:
    ports:
      - "8008:8000"
    networks:
      default:
        ipv4_address: 172.18.0.65

  sync-service:
    ports:
      - "8012:8000"
    networks:
      default:
        ipv4_address: 172.18.0.66

  postgres_sync:
    ports:
      - "${PG_SYNC_PORT}:5432"
    networks:
      default:
        ipv4_address: 172.18.0.67

  load-service-1:
    ports:
      - "8101:8000"
    networks:
      default:
        ipv4_address: 172.18.0.68

  load-service-2:
    ports:
      - "8102:8000"
    networks:
      default:
        ipv4_address: 172.18.0.69

  load-service-celery-beat-0:
    networks:
      default:
        ipv4_address: 172.18.0.70

  load-service-celery-beat-1:
    networks:
      default:
        ipv4_address: 172.18.0.71

  load-service-celery-beat-2:
    networks:
      default:
        ipv4_address: 172.18.0.72

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1