services:
  broker-1:
    ports:
      - "39092:39092"

  etl_ugc:
    build:
      context: ./etl_ugc
      dockerfile: ./docker/Dockerfile

  clickhouse-node1:
    ports:
      - "8123:8123"
      - "9000:9000"

  ugc_service:
    build:
      context: ./ugc
      dockerfile: ./docker/Dockerfile
      target: development
    volumes:
      - ./ugc/src:/opt/app
    ports:
        - "8001:8001"

  auth:
    build:
      context: auth
      dockerfile: ./docker/Dockerfile
      target: development
    ports:
      - "5000:5000"

  redis_auth:
    ports:
      - "${REDIS_AUTH_PORT}:6379"

  postgres_auth:
    ports:
      - "${PG_AUTH_PORT}:5432"
