# docker-compose.yaml
name: s3-storage
services:
 minio1:
   image: minio/minio:latest
   container_name: minio_1
   command: server --console-address ":9001" /data/
   ports:
     - "9000:9000"
     - "9001:9001"
   environment:
     MINIO_ROOT_USER: root
     MINIO_ROOT_PASSWORD: 123456qwe
   volumes:
     - minio-storage_1:/data
   healthcheck:
     test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
     interval: 30s
     timeout: 20s
     retries: 3

 minio2:
   image: minio/minio:latest
   container_name: minio_2
   command: server --console-address ":9001" /data/
   ports:
     - "19000:9000"
     - "19001:9001"
   environment:
     MINIO_ROOT_USER: root
     MINIO_ROOT_PASSWORD: 123456qwe
   volumes:
     - minio-storage_2:/data
   healthcheck:
     test: ["CMD", "curl", "-f", "http://localhost:19000/minio/health/live"]
     interval: 30s
     timeout: 20s
     retries: 3

volumes:
  minio-storage_1:
  minio-storage_2:

networks:
  default:
    name: s3-network