version: '3.7'

services:


  minio:
    image: quay.io/minio/minio:RELEASE.2022-10-24T18-35-07Z
    container_name: minio
    command: server /data --console-address ":9001"
    env_file:
      - .env
    ports:
      - '9000:9000'
      - '9001:9001'
    restart: unless-stopped


volumes:
  pgdata:
  rabbitmq:
